### ISSUE TITLE
If project loading is cancelled, V4MD might throw a NPE

### ISSUE THREAD

**Issue by ujhelyiz** [viatra/v4md#23]
If project loading is cancelled with V4MD installed and enabled, we might receive a NPE with the following trace:

```
java.lang.NullPointerException
	at com.incquerylabs.v4md.ViatraQueryAdapter.getAdapter(ViatraQueryAdapter.java:48)
	at com.incquerylabs.v4md.ViatraQueryAdapter.disposeAdapter(ViatraQueryAdapter.java:70)
	at com.incquerylabs.v4md.V4MDPlugin$1.projectPreClosed(V4MDPlugin.java:22)
	at com.nomagic.magicdraw.core.project.ProjectsManager.fireProjectPreClosed(ProjectsManager.java:1753)
	at com.nomagic.magicdraw.core.project.c.b(c.java:78)
	at com.nomagic.magicdraw.core.project.c.a(c.java:176)
	at com.nomagic.magicdraw.actions.ActionsExecuter.closeProjectSave(ActionsExecuter.java:1103)
	at com.nomagic.magicdraw.core.project.ProjectsManager.lambda$closeProjectNoSave$7(ProjectsManager.java:748)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:301)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.nomagic.utils.EventTracker.dispatchEvent(EventTracker.java:31)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:109)
	at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:184)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:229)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:227)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:227)
	at java.awt.Dialog.show(Dialog.java:1084)
	at com.nomagic.ui.Dialog.toFrontAndShow(Dialog.java:137)
	at com.nomagic.ui.Dialog.show(Dialog.java:127)
	at java.awt.Component.show(Component.java:1671)
	at java.awt.Component.setVisible(Component.java:1623)
	at java.awt.Window.setVisible(Window.java:1014)
	at java.awt.Dialog.setVisible(Dialog.java:1005)
	at com.nomagic.ui.Dialog.setVisible(Dialog.java:389)
	at com.nomagic.ui.BaseProgressMonitor.showDialogIfNeeded(BaseProgressMonitor.java:372)
	at com.nomagic.ui.BaseProgressMonitor.showDialog(BaseProgressMonitor.java:290)
	at com.nomagic.ui.BaseProgressMonitor.start(BaseProgressMonitor.java:671)
	at com.nomagic.ui.e.a(e.java:26)
	at com.nomagic.magicdraw.ui.bp.a(bp.java:34)
	at com.nomagic.ui.BaseProgressMonitor.executeTaskWithProgressMonitor(BaseProgressMonitor.java:780)
	at com.nomagic.magicdraw.ui.ProgressMonitor.showProgress(ProgressMonitor.java:70)
	at com.nomagic.magicdraw.ui.ProgressMonitor.showProgress(ProgressMonitor.java:60)
	at com.nomagic.magicdraw.ui.ProgressMonitor.showProgress(ProgressMonitor.java:55)
	at com.nomagic.magicdraw.persistence.ProjectLoadService.loadAndHandleErrorsOnTask(ProjectLoadService.java:170)
	at com.nomagic.magicdraw.persistence.ProjectLoadService.loadAndHandleErrorsOnTask(ProjectLoadService.java:153)
	at com.nomagic.magicdraw.persistence.xmi.load.model.utils.ProjectLoader.lambda$loadProjectOnTask$0(ProjectLoader.java:101)
	at com.nomagic.magicdraw.persistence.xmi.load.model.utils.ProjectLoader.loadProject(ProjectLoader.java:153)
	at com.nomagic.magicdraw.persistence.xmi.load.model.utils.ProjectLoader.loadProjectOnTask(ProjectLoader.java:101)
	at com.nomagic.magicdraw.actions.ActionsExecuter.openProjectAction(ActionsExecuter.java:827)
	at com.nomagic.magicdraw.actions.ActionsExecuter.openProjectAction(ActionsExecuter.java:791)
	at com.nomagic.magicdraw.actions.ActionsExecuter.openProjectAction(ActionsExecuter.java:775)
	at com.nomagic.magicdraw.actions.ActionsExecuter.openProjectAction(ActionsExecuter.java:764)
	at com.nomagic.magicdraw.hyperlinks.ExternalElementURLActivator.openLocalProject(ExternalElementURLActivator.java:439)
	at com.nomagic.magicdraw.hyperlinks.ExternalElementURLActivator.openExternalURL(ExternalElementURLActivator.java:95)
	at com.nomagic.magicdraw.hyperlinks.ElementHyperlinkHandler.activate(ElementHyperlinkHandler.java:148)
	at com.nomagic.magicdraw.hyperlinks.ElementHyperlinkHandler.activate(ElementHyperlinkHandler.java:123)
	at com.nomagic.magicdraw.ui.actions.s$b.actionPerformed(s$b.java:193)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
	at com.apple.laf.ScreenMenuItem.actionPerformed(ScreenMenuItem.java:125)
	at java.awt.MenuItem.processActionEvent(MenuItem.java:669)
	at java.awt.MenuItem.processEvent(MenuItem.java:628)
	at java.awt.MenuComponent.dispatchEventImpl(MenuComponent.java:351)
	at java.awt.MenuComponent.dispatchEvent(MenuComponent.java:339)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:761)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at com.nomagic.utils.EventTracker.dispatchEvent(EventTracker.java:31)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by ujhelyiz** [comment]
Should be fixed by better handling of missing projects during unloading.
