### ISSUE TITLE
IllegalStateException (Duplicate deletion of tuple T) during opening of a locally saved TWC project

### ISSUE THREAD

**Issue by tamasborbas** [viatra/v4md#58]
We have an `engine.getBaseIndex().coalesceTraversal()` call in the `projectOpened` method of a `ProjectEventListenerAdapter` in which we catch the following exception in case if we open a TWC project with locally saved changes and in it we have an opened diagram with legend using VIATRA query:

```stacktrace
java.lang.IllegalStateException: Duplicate deletion of tuple T(com.nomagic.uml2.ext.magicdraw.classes.mdkernel.impl.ClassImpl@d06cf784;com.nomagic.uml2.ext.magicdraw.classes.mdkernel.impl.PropertyImpl@9fefa6d6;) from [1413]GenericProjectionIndexer([1407]JoinNode->[com..legend.NewParts]/M(2->0,))->[com..legend.NewParts]
	at org.eclipse.viatra.query.runtime.matchers.memories.MaskedTupleMemory.raiseDuplicateDeletion(MaskedTupleMemory.java:377)
	at org.eclipse.viatra.query.runtime.matchers.memories.UnaryMaskedTupleMemory.removeInternal(UnaryMaskedTupleMemory.java:139)
	at org.eclipse.viatra.query.runtime.matchers.memories.UnaryMaskedTupleMemory.remove(UnaryMaskedTupleMemory.java:109)
	at org.eclipse.viatra.query.runtime.rete.index.IndexerWithMemory$2.update(IndexerWithMemory.java:273)
	at org.eclipse.viatra.query.runtime.rete.index.IndexerWithMemory.update(IndexerWithMemory.java:129)
	at org.eclipse.viatra.query.runtime.rete.network.mailbox.timeless.BehaviorChangingMailbox.postMessage(BehaviorChangingMailbox.java:53)
	at org.eclipse.viatra.query.runtime.rete.network.StandardNode.propagateUpdate(StandardNode.java:49)
	at org.eclipse.viatra.query.runtime.rete.index.JoinNode.access$1(JoinNode.java:1)
	at org.eclipse.viatra.query.runtime.rete.index.JoinNode$1.notifyUpdate(JoinNode.java:81)
	at org.eclipse.viatra.query.runtime.rete.index.DualInputNode$1.notifyIndexerUpdate(DualInputNode.java:121)
	at org.eclipse.viatra.query.runtime.rete.index.StandardIndexer.propagate(StandardIndexer.java:52)
	at org.eclipse.viatra.query.runtime.rete.index.GenericProjectionIndexer.update(GenericProjectionIndexer.java:40)
	at org.eclipse.viatra.query.runtime.rete.index.IndexerWithMemory$2.update(IndexerWithMemory.java:274)
	at org.eclipse.viatra.query.runtime.rete.index.IndexerWithMemory.update(IndexerWithMemory.java:129)
	at org.eclipse.viatra.query.runtime.rete.network.mailbox.timeless.DefaultMailbox.deliverAll(DefaultMailbox.java:134)
	at org.eclipse.viatra.query.runtime.rete.network.mailbox.timeless.BehaviorChangingMailbox.deliverAll(BehaviorChangingMailbox.java:61)
	at org.eclipse.viatra.query.runtime.rete.network.communication.timeless.SingletonCommunicationGroup.deliverMessages(SingletonCommunicationGroup.java:42)
	at org.eclipse.viatra.query.runtime.rete.network.ReteContainer.deliverMessagesSingleThreaded(ReteContainer.java:579)
	at org.eclipse.viatra.query.runtime.rete.network.Network.waitForReteTermination(Network.java:346)
	at org.eclipse.viatra.query.runtime.rete.boundary.ExternalInputEnumeratorNode.update(ExternalInputEnumeratorNode.java:172)
	at org.eclipse.viatra.query.runtime.emf.EMFQueryRuntimeContext$EStructuralFeatureInstancesKeyAdapter.featureInserted(EMFQueryRuntimeContext.java:745)
	at org.eclipse.viatra.query.runtime.base.core.NavigationHelperImpl.notifyFeatureListeners(NavigationHelperImpl.java:699)
	at org.eclipse.viatra.query.runtime.base.core.EMFBaseIndexInstanceStore.insertFeatureTuple(EMFBaseIndexInstanceStore.java:276)
	at org.eclipse.viatra.query.runtime.base.core.NavigationHelperVisitor.visitAttribute(NavigationHelperVisitor.java:304)
	at org.eclipse.viatra.query.runtime.base.comprehension.EMFModelComprehension.traverseFeatureInternal(EMFModelComprehension.java:268)
	at org.eclipse.viatra.query.runtime.base.comprehension.EMFModelComprehension.traverseFeatureTargets(EMFModelComprehension.java:222)
	at org.eclipse.viatra.query.runtime.base.comprehension.EMFModelComprehension.traverseObject(EMFModelComprehension.java:203)
	at org.eclipse.viatra.query.runtime.base.comprehension.EMFModelComprehension.traverseObjectIfUnfiltered(EMFModelComprehension.java:188)
	at org.eclipse.viatra.query.runtime.base.comprehension.EMFModelComprehension.traverseFeatureInternal(EMFModelComprehension.java:292)
	at org.eclipse.viatra.query.runtime.base.comprehension.EMFModelComprehension.traverseFeatureTargets(EMFModelComprehension.java:217)
	at org.eclipse.viatra.query.runtime.base.comprehension.EMFModelComprehension.traverseObject(EMFModelComprehension.java:203)
	...
	at org.eclipse.viatra.query.runtime.base.comprehension.EMFModelComprehension.traverseObject(EMFModelComprehension.java:203)
	at org.eclipse.viatra.query.runtime.base.comprehension.EMFModelComprehension.traverseObjectIfUnfiltered(EMFModelComprehension.java:188)
	at org.eclipse.viatra.query.runtime.base.comprehension.EMFModelComprehension.traverseFeatureInternal(EMFModelComprehension.java:292)
	at org.eclipse.viatra.query.runtime.base.comprehension.EMFModelComprehension.traverseFeatureTargets(EMFModelComprehension.java:217)
	at org.eclipse.viatra.query.runtime.base.comprehension.EMFModelComprehension.traverseObject(EMFModelComprehension.java:203)
	at org.eclipse.viatra.query.runtime.base.comprehension.EMFModelComprehension.traverseModel(EMFModelComprehension.java:143)
	at org.eclipse.viatra.query.runtime.base.core.NavigationHelperImpl.traverse(NavigationHelperImpl.java:1296)
	at org.eclipse.viatra.query.runtime.base.core.NavigationHelperImpl$1.call(NavigationHelperImpl.java:1270)
	at org.eclipse.viatra.query.runtime.base.core.NavigationHelperImpl.coalesceTraversals(NavigationHelperImpl.java:1144)
	at org.eclipse.viatra.query.runtime.emf.EMFBaseIndexWrapper.coalesceTraversals(EMFBaseIndexWrapper.java:58)
```

**Software Versions**
* Cameo Systems Modeler: 19.0 SP3
* v4md: 2.3.0/2.4.0 (tried both with matching Viatra)

**Comment by ujhelyiz** [comment]
We had a look at this issue on @tamasborbas's computer and found that before this exception was thrown after the query engine was initialized before the project was loaded completely and an NPE was thrown during engine initialization. This means the engine was in an inconsistent state that might explain the duplicate deletion events as well.
