### ISSUE TITLE
Multi-threaded environment not handled properly

### ISSUE THREAD

**Issue by tamasborbas** [viatra/v4md#61]
We got the following exceptions probably because of multi-threaded environment:

```
java.util.ConcurrentModificationExceptionjava.util.ConcurrentModificationException at
java.util.ArrayList.forEach(ArrayList.java:1260) at
com.incquerylabs.v4md.ViatraQueryAdapter.lambda$null$2(ViatraQueryAdapter.java:128) at
org.eclipse.viatra.query.runtime.base.core.NavigationHelperImpl.coalesceTraversals(NavigationHelperImpl.java:1144) at
org.eclipse.viatra.query.runtime.emf.EMFBaseIndexWrapper.coalesceTraversals(EMFBaseIndexWrapper.java:58) at
com.incquerylabs.v4md.ViatraQueryAdapter.lambda$initializeEngine$3(ViatraQueryAdapter.java:127) at
java.util.Optional.map(Optional.java:215) at
com.incquerylabs.v4md.ViatraQueryAdapter.initializeEngine(ViatraQueryAdapter.java:124) at
com.incquerylabs.v4md.ViatraQueryAdapter.executeActionOnEngine(ViatraQueryAdapter.java:116) at
...ViatraQueryInitializer.projectOpened(ViatraQueryInitializer.java:23) at
com.nomagic.magicdraw.core.project.ProjectsManager.fireProjectOpened(ProjectsManager.java:1530) at
com.nomagic.magicdraw.persistence.ci.updaters.k.a(k.java:32) at
com.nomagic.magicdraw.persistence.ci.updaters.ak$b.u(ak$b.java:316) at
com.nomagic.magicdraw.persistence.ci.updaters.ak.w(ak.java:479) at
com.nomagic.magicdraw.persistence.ci.updaters.ak.b(ak.java:469) at
com.nomagic.magicdraw.persistence.ci.updaters.aj.a(aj.java:75) at
com.nomagic.magicdraw.persistence.ci.updaters.aj.postOperation(aj.java:61) at
com.nomagic.ci.persistence.spi.events.DefaultComplexOperationEventService$ComplexEventSupport.notify(DefaultComplexOperationEventService.java:454) at
com.nomagic.ci.persistence.spi.events.DefaultComplexOperationEventService$ComplexEventSupport.notify(DefaultComplexOperationEventService.java:1) at com.nomagic.ci.event.AbstractEventSupport.fireEvent(AbstractEventSupport.java:130) at
com.nomagic.ci.persistence.spi.events.DefaultComplexOperationEventService.createAndDeliverEvent(DefaultComplexOperationEventService.java:92) at com.nomagic.magicdraw.esi.project.project.g.a(g.java:148) at
com.nomagic.magicdraw.esi.project.project.g.access$500(g.java:30) at
com.nomagic.magicdraw.esi.project.project.g$c.a(g$c.java:194) at
com.nomagic.magicdraw.esi.project.project.g$c.a(g$c.java:199) at com.nomagic.magicdraw.esi.project.project.g.a(g.java:75) at
com.nomagic.magicdraw.esi.project.project.af.a(af.java:301) at com.nomagic.magicdraw.esi.project.project.af.a(af.java:182) at
com.nomagic.magicdraw.esi.project.project.ag.a(ag.java:122) at
com.nomagic.magicdraw.esi.project.project.ag.openProject(ag.java:109) at
com.nomagic.magicdraw.persistence.ProjectLoadService.loadStorage(ProjectLoadService.java:661) at
com.nomagic.magicdraw.persistence.ProjectLoadService.lambda$doLoad$0(ProjectLoadService.java:413) at
com.nomagic.magicdraw.persistence.ProjectLoadService.loadWithLoader(ProjectLoadService.java:449) at
com.nomagic.magicdraw.persistence.ProjectLoadService.doLoad(ProjectLoadService.java:412) at
com.nomagic.magicdraw.persistence.ProjectLoadService.load(ProjectLoadService.java:405) at
com.nomagic.magicdraw.teamwork2.esi.EsiServerActionsExecuter$4.execute(EsiServerActionsExecuter.java:978) at
com.nomagic.task.Task.construct(Task.java:192) at com.nomagic.task.SwingWorker$2.call(SwingWorker.java:209) at
java.util.concurrent.FutureTask.run(FutureTask.java:266) at
com.nomagic.task.SwingWorker$SwingWorkerFuture.run(SwingWorker.java:596) at
com.nomagic.task.BackportedThreadPoolExecutor$Worker.runTask(BackportedThreadPoolExecutor.java:1593) at
com.nomagic.task.BackportedThreadPoolExecutor$Worker.run(BackportedThreadPoolExecutor.java:1624) at
com.nomagic.task.PooledThread.run(PooledThread.java:64)2020-09-16 18:35:33,993 [pool-MagicDraw-thread-1:Open Project] ERROR com.incquerylabs.v4md.ViatraQueryAdapter - Required actions cannot be executed on the VIATRA engine!java.lang.reflect.InvocationTargetException at
org.eclipse.viatra.query.runtime.base.core.NavigationHelperImpl.coalesceTraversals(NavigationHelperImpl.java:1170) at
org.eclipse.viatra.query.runtime.emf.EMFBaseIndexWrapper.coalesceTraversals(EMFBaseIndexWrapper.java:58) at
com.incquerylabs.v4md.ViatraQueryAdapter.lambda$initializeEngine$3(ViatraQueryAdapter.java:127) at
java.util.Optional.map(Optional.java:215) at
com.incquerylabs.v4md.ViatraQueryAdapter.initializeEngine(ViatraQueryAdapter.java:124) at
com.incquerylabs.v4md.ViatraQueryAdapter.executeActionOnEngine(ViatraQueryAdapter.java:116) at
...ViatraQueryInitializer.projectOpened(ViatraQueryInitializer.java:23) at
com.nomagic.magicdraw.core.project.ProjectsManager.fireProjectOpened(ProjectsManager.java:1530) at
com.nomagic.magicdraw.persistence.ci.updaters.k.a(k.java:32) at
com.nomagic.magicdraw.persistence.ci.updaters.ak$b.u(ak$b.java:316) at
com.nomagic.magicdraw.persistence.ci.updaters.ak.w(ak.java:479) at
com.nomagic.magicdraw.persistence.ci.updaters.ak.b(ak.java:469) at
com.nomagic.magicdraw.persistence.ci.updaters.aj.a(aj.java:75) at
com.nomagic.magicdraw.persistence.ci.updaters.aj.postOperation(aj.java:61) at
com.nomagic.ci.persistence.spi.events.DefaultComplexOperationEventService$ComplexEventSupport.notify(DefaultComplexOperationEventService.java:454) at
com.nomagic.ci.persistence.spi.events.DefaultComplexOperationEventService$ComplexEventSupport.notify(DefaultComplexOperationEventService.java:1) at com.nomagic.ci.event.AbstractEventSupport.fireEvent(AbstractEventSupport.java:130) at
com.nomagic.ci.persistence.spi.events.DefaultComplexOperationEventService.createAndDeliverEvent(DefaultComplexOperationEventService.java:92) at com.nomagic.magicdraw.esi.project.project.g.a(g.java:148) at
com.nomagic.magicdraw.esi.project.project.g.access$500(g.java:30) at
com.nomagic.magicdraw.esi.project.project.g$c.a(g$c.java:194) at
com.nomagic.magicdraw.esi.project.project.g$c.a(g$c.java:199) at com.nomagic.magicdraw.esi.project.project.g.a(g.java:75) at
com.nomagic.magicdraw.esi.project.project.af.a(af.java:301) at com.nomagic.magicdraw.esi.project.project.af.a(af.java:182) at
com.nomagic.magicdraw.esi.project.project.ag.a(ag.java:122) at
com.nomagic.magicdraw.esi.project.project.ag.openProject(ag.java:109) at
com.nomagic.magicdraw.persistence.ProjectLoadService.loadStorage(ProjectLoadService.java:661) at
com.nomagic.magicdraw.persistence.ProjectLoadService.lambda$doLoad$0(ProjectLoadService.java:413) at
com.nomagic.magicdraw.persistence.ProjectLoadService.loadWithLoader(ProjectLoadService.java:449) at
com.nomagic.magicdraw.persistence.ProjectLoadService.doLoad(ProjectLoadService.java:412) at
com.nomagic.magicdraw.persistence.ProjectLoadService.load(ProjectLoadService.java:405) at
com.nomagic.magicdraw.teamwork2.esi.EsiServerActionsExecuter$4.execute(EsiServerActionsExecuter.java:978) at
com.nomagic.task.Task.construct(Task.java:192) at com.nomagic.task.SwingWorker$2.call(SwingWorker.java:209) at
java.util.concurrent.FutureTask.run(FutureTask.java:266) at
com.nomagic.task.SwingWorker$SwingWorkerFuture.run(SwingWorker.java:596) at
com.nomagic.task.BackportedThreadPoolExecutor$Worker.runTask(BackportedThreadPoolExecutor.java:1593) at
com.nomagic.task.BackportedThreadPoolExecutor$Worker.run(BackportedThreadPoolExecutor.java:1624) at
com.nomagic.task.PooledThread.run(PooledThread.java:64)Caused by: java.util.ConcurrentModificationException at
java.util.ArrayList.forEach(ArrayList.java:1260) at
com.incquerylabs.v4md.ViatraQueryAdapter.lambda$null$2(ViatraQueryAdapter.java:128) at
org.eclipse.viatra.query.runtime.base.core.NavigationHelperImpl.coalesceTraversals(NavigationHelperImpl.java:1144) ...
39 more
```

```
java.lang.IllegalStateException: Trying to use a Rete engine that has been disposed or has not yet been initialized.java.lang.IllegalStateException: Trying to use a Rete engine that has been disposed or has not yet been initialized. at
org.eclipse.viatra.query.runtime.rete.matcher.ReteEngine.ensureInitialized(ReteEngine.java:532) at
org.eclipse.viatra.query.runtime.rete.matcher.ReteEngine.accessProjection(ReteEngine.java:359) at
org.eclipse.viatra.query.runtime.rete.matcher.RetePatternMatcher.count(RetePatternMatcher.java:151) at
org.eclipse.viatra.query.runtime.rete.matcher.RetePatternMatcher.count(RetePatternMatcher.java:141) at
org.eclipse.viatra.query.runtime.rete.matcher.RetePatternMatcher.countMatches(RetePatternMatcher.java:401) at
org.eclipse.viatra.query.runtime.rete.matcher.RetePatternMatcher.hasMatch(RetePatternMatcher.java:391) at
org.eclipse.viatra.query.runtime.api.impl.BaseMatcher.rawHasMatch(BaseMatcher.java:171) at 
```

**Comment by tamasborbas** [comment]
The synchronization of the necessary methods shall solve the problem.
