### ISSUE TITLE
2021x - Refresh 1: IncrementalTransformationSynchronizer is broken

### ISSUE THREAD

**Issue by TheKorpos** [viatra/v4md#74]
* Stacktrace:

java.lang.NoSuchMethodError: 'void com.nomagic.uml2.synchronizer.TransactionBasedSynchronizer.<init>(com.nomagic.magicdraw.core.Project)'
	at com.incquerylabs.v4md.transformations.IncrementalTransformationSynchronizer.<init>(IncrementalTransformationSynchronizer.java:71)
	at java.base/java.util.Map.computeIfAbsent(Map.java:1003)
	at com.incquerylabs.v4md.transformations.IncrementalTransformationSynchronizer$ViatraTransformationSynchronizerManager.apply(IncrementalTransformationSynchronizer.java:57)
	at com.incquerylabs.v4md.transformations.IncrementalTransformationSynchronizer$ViatraTransformationSynchronizerManager.apply(IncrementalTransformationSynchronizer.java:47)

 * Cause
com.nomagic.uml2.synchronizer.TransactionBasedSynchronizer is now uses generic template parameters

``` public abstract class TransactionBasedSynchronizer<P extends ElementProject> ```

 * Potential fix:
I belive that adding ```<Project>``` to the class' header solves the problem.

```public class IncrementalTransformationSynchronizer extends TransactionBasedSynchronizer<Project>```

**Comment by TheKorpos** [comment]
This happens on project load and prevents me even opening the project.

**Comment by TheKorpos** [comment]
V4MD version I used is 2.5.2
